### ISSUE TITLE
Add codebase visualization using glato/emerge

### ISSUE THREAD

**Issue by tom-leamon** [AVsync-LIVE/Harmony#107]
![image](https://user-images.githubusercontent.com/18317587/212461167-4706e367-8cff-44c2-b881-b1ef9eee2c71.png)

Github action:
```
name: Emerge
on:
  push:
    branches:
      - main

jobs:
  emerge:
    runs-on: ubuntu-latest

steps:
- name: Setup Python
  run: |
    sudo apt-get install -y python3-pip
    pip3 install --upgrade pip
    pip3 install emerge-scan
- name: Create emerge-graph directory
  run: mkdir -p $GITHUB_WORKSPACE/emerge-graph
- name: Run Emerge
  run: emerge-scan -p $GITHUB_WORKSPACE -c config.yml -o $GITHUB_WORKSPACE/emerge-graph
- name: Upload Graph
  uses: actions/upload-artifact@v2
  with:
    name: emerge-graph
    path: $GITHUB_WORKSPACE/emerge-graph
```

Emerge config file. Don't forget to add the `emerge-graph` folder
```
scan:
  path: $GITHUB_WORKSPACE
  languages:
    - typescript
  ignore:
    - dist
    - build

extract:
  classes: true

metrics:
  sloc: true
  fan_in_out: true
  modularity: true

output:
  format: graphml
  path: $GITHUB_WORKSPACE/emerge-graph
```
